In [1]:
#Overview of Student's performance in Math subject
import pandas as pd
import zipfile
with zipfile.ZipFile('/content/archive.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')
df = pd.read_csv('student_math_clean.csv')
df.head()

,student_id,school,sex,age,address_type,family_size,parent_status,mother_education,father_education,mother_job,...,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
0,1,GP,F,18,Urban,Greater than 3,Apart,higher education,higher education,at_home,...,4,3,4,1,1,3,6,5,6,6
1,2,GP,F,17,Urban,Greater than 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,5,3,3,1,1,3,4,5,5,6
2,3,GP,F,15,Urban,Less than or equal to 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,4,3,2,2,3,3,10,7,8,10
3,4,GP,F,15,Urban,Greater than 3,Living together,higher education,5th to 9th grade,health,...,3,2,2,1,1,5,2,15,14,15
4,5,GP,F,16,Urban,Greater than 3,Living together,secondary education,secondary education,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             395 non-null    int64
 1   school                 395 non-null    object
 2   sex                    395 non-null    object
 3   age                    395 non-null    int64
 4   address_type           395 non-null    object
 5   family_size            395 non-null    object
 6   parent_status          395 non-null    object
 7   mother_education       395 non-null    object
 8   father_education       395 non-null    object
 9   mother_job             395 non-null    object
 10  father_job             395 non-null    object
 11  school_choice_reason   395 non-null    object
 12  guardian               395 non-null    object
 13  travel_time            395 non-null    object
 14  study_time             395 non-null    object
 15  class_failures         395 non-null    int64
 16  school_support         395 non-null    object
 17  family_support         395 non-null    object
 18  extra_paid_classes     395 non-null    object
 19  activities             395 non-null    object
 20  nursery_school         395 non-null    object
 21  higher_ed              395 non-null    object
 22  internet_access        395 non-null    object
 23  romantic_relationship  395 non-null    object
 24  family_relationship    395 non-null    int64
 25  free_time              395 non-null    int64
 26  social                 395 non-null    int64
 27  weekday_alcohol        395 non-null    int64
 28  weekend_alcohol        395 non-null    int64
 29  health                 395 non-null    int64
 30  absences               395 non-null    int64
 31  grade_1                395 non-null    int64
 32  grade_2                395 non-null    int64
 33  final_grade            395 non-null    int64
dtypes: int64(13), object(21)
memory usage: 105.0+ KB

**Encoding**

In [2]:
#Binary: Misc
df["school"] = df["school"].replace({"MS": 1, "GP": 0})
df["sex"] = df["sex"].replace({"F": 1, "M": 0})
df["address_type"] = df["address_type"].replace({"Urban": 1, "Rural": 0})
df["family_size"] = df["family_size"].replace({"Greater than 3": 1, "Less than or equal to 3": 0})
df["parent_status"] = df["parent_status"].replace({"Living together": 1, "Apart": 0})

#Binary: Yes/No
df["school_support"] = df["school_support"].replace({"yes": 1, "no": 0})
df["family_support"] = df["family_support"].replace({"yes": 1, "no": 0})
df["extra_paid_classes"] = df["extra_paid_classes"].replace({"yes": 1, "no": 0})
df["activities"] = df["activities"].replace({"yes": 1, "no": 0})
df["nursery_school"] = df["nursery_school"].replace({"yes": 1, "no": 0})
df["higher_ed"] = df["higher_ed"].replace({"yes": 1, "no": 0})
df["internet_access"] = df["internet_access"].replace({"yes": 1, "no": 0})
df["romantic_relationship"] = df["romantic_relationship"].replace({"yes": 1, "no": 0})

<ipython-input-2-28a7d834a49e>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["school"] = df["school"].replace({"MS": 1, "GP": 0})
<ipython-input-2-28a7d834a49e>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["sex"] = df["sex"].replace({"F": 1, "M": 0})
<ipython-input-2-28a7d834a49e>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["address_type"] = df["address_type"].replace({"Urban": 1, "Rural": 0})
<ipython-input-2-28a7d834a49e>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["family_size"] = df["family_size"].replace({"Greater than 3": 1, "Less than or equal to 3": 0})
<ipython-input-2-28a7d834a49e>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["parent_status"] = df["parent_status"].replace({"Living together": 1, "Apart": 0})
<ipython-input-2-28a7d834a49e>:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["school_support"] = df["school_support"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["family_support"] = df["family_support"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["extra_paid_classes"] = df["extra_paid_classes"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["activities"] = df["activities"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["nursery_school"] = df["nursery_school"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["higher_ed"] = df["higher_ed"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["internet_access"] = df["internet_access"].replace({"yes": 1, "no": 0})
<ipython-input-2-28a7d834a49e>:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["romantic_relationship"] = df["romantic_relationship"].replace({"yes": 1, "no": 0})

In [3]:
#Ordinal
travel = {'<15 min.': 0, '15 to 30 min.': 1, '30 min. to 1 hour': 2, '>1 hour':3}
df["travel_time"] = df["travel_time"].map(travel)

study = {'<2 hours': 0, '2 to 5 hours': 1, '5 to 10 hours': 2, '>10 hours':3}
df["study_time"] = df["study_time"].map(study)

In [4]:
#One-hot
categorical_cols = ["mother_education", "mother_job", "father_education", "father_job", "school_choice_reason", "guardian"]
encoded_df = pd.get_dummies(df, columns=categorical_cols, prefix=categorical_cols, prefix_sep='_')

In [ ]:
df["school_choice_reason"].value_counts()

school_choice_reason
course        145
home          109
reputation    105
other          36
Name: count, dtype: int64

In [ ]:
encoded_df

,student_id,school,sex,age,address_type,family_size,parent_status,travel_time,study_time,class_failures,...,father_job_other,father_job_services,father_job_teacher,school_choice_reason_course,school_choice_reason_home,school_choice_reason_other,school_choice_reason_reputation,guardian_father,guardian_mother,guardian_other
0,1,0,1,18,1,1,0,1,1,0,...,False,False,True,True,False,False,False,False,True,False
1,2,0,1,17,1,1,1,0,1,0,...,True,False,False,True,False,False,False,True,False,False
2,3,0,1,15,1,0,1,0,1,3,...,True,False,False,False,False,True,False,False,True,False
3,4,0,1,15,1,1,1,0,2,0,...,False,True,False,False,True,False,False,False,True,False
4,5,0,1,16,1,1,1,0,1,0,...,True,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,391,1,0,20,1,0,0,0,1,2,...,False,True,False,True,False,False,False,False,False,True
391,392,1,0,17,1,0,1,1,0,0,...,False,True,False,True,False,False,False,False,True,False
392,393,1,0,21,0,1,1,0,0,3,...,True,False,False,True,False,False,False,False,False,True
393,394,1,0,18,0,0,1,2,0,0,...,True,False,False,True,False,False,False,False,True,False
394,395,1,0,19,1,0,1,0,0,0,...,False,False,False,True,False,False,False,True,False,False

In [5]:
encoded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 55 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   student_id                                      395 non-null    int64
 1   school                                          395 non-null    int64
 2   sex                                             395 non-null    int64
 3   age                                             395 non-null    int64
 4   address_type                                    395 non-null    int64
 5   family_size                                     395 non-null    int64
 6   parent_status                                   395 non-null    int64
 7   travel_time                                     395 non-null    int64
 8   study_time                                      395 non-null    int64
 9   class_failures                                  395 non-null    int64
 10  school_support                                  395 non-null    int64
 11  family_support                                  395 non-null    int64
 12  extra_paid_classes                              395 non-null    int64
 13  activities                                      395 non-null    int64
 14  nursery_school                                  395 non-null    int64
 15  higher_ed                                       395 non-null    int64
 16  internet_access                                 395 non-null    int64
 17  romantic_relationship                           395 non-null    int64
 18  family_relationship                             395 non-null    int64
 19  free_time                                       395 non-null    int64
 20  social                                          395 non-null    int64
 21  weekday_alcohol                                 395 non-null    int64
 22  weekend_alcohol                                 395 non-null    int64
 23  health                                          395 non-null    int64
 24  absences                                        395 non-null    int64
 25  grade_1                                         395 non-null    int64
 26  grade_2                                         395 non-null    int64
 27  final_grade                                     395 non-null    int64
 28  mother_education_5th to 9th grade               395 non-null    bool
 29  mother_education_higher education               395 non-null    bool
 30  mother_education_none                           395 non-null    bool
 31  mother_education_primary education (4th grade)  395 non-null    bool
 32  mother_education_secondary education            395 non-null    bool
 33  mother_job_at_home                              395 non-null    bool
 34  mother_job_health                               395 non-null    bool
 35  mother_job_other                                395 non-null    bool
 36  mother_job_services                             395 non-null    bool
 37  mother_job_teacher                              395 non-null    bool
 38  father_education_5th to 9th grade               395 non-null    bool
 39  father_education_higher education               395 non-null    bool
 40  father_education_none                           395 non-null    bool
 41  father_education_primary education (4th grade)  395 non-null    bool
 42  father_education_secondary education            395 non-null    bool
 43  father_job_at_home                              395 non-null    bool
 44  father_job_health                               395 non-null    bool
 45  father_job_other                                395 non-null    bool
 46  father_job_services                             395 non-null    bool
 47  father_job_teacher                              395 non-null    bool
 48  school_choice_reason_course                     395 non-null    bool
 49  school_choice_reason_home                       395 non-null    bool
 50  school_choice_reason_other                      395 non-null    bool
 51  school_choice_reason_reputation                 395 non-null    bool
 52  guardian_father                                 395 non-null    bool
 53  guardian_mother                                 395 non-null    bool
 54  guardian_other                                  395 non-null    bool
dtypes: bool(27), int64(28)
memory usage: 96.9 KB

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

correlation_matrix = encoded_df.drop(["student_id"], axis = 1).corr()  # Calculate the correlation matrix

plt.figure(figsize=(30,30))
sns.heatmap(correlation_matrix, annot=True, square=True,
            cmap='RdBu', vmax=1, vmin=-1)
plt.title('Correlations Between Variables', size=18)
plt.xticks(size=13)
plt.yticks(size=13)
plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import pandas as pd
import numpy as np

# Assuming 'correlation_matrix' is your correlation matrix
correlation_matrix = encoded_df.drop(["student_id"], axis=1).corr()

# Set the threshold
threshold = 0.7

# Get pairs with high correlation
highly_correlated_pairs = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i + 1, len(correlation_matrix.columns)):
        if abs(correlation_matrix.iloc[i, j]) > threshold:
            highly_correlated_pairs.append(
                (correlation_matrix.columns[i], correlation_matrix.columns[j], correlation_matrix.iloc[i, j])
            )

# Print the highly correlated pairs
print("Highly Correlated Pairs (above threshold of 0.7):")
for pair in highly_correlated_pairs:
    print(f"{pair[0]} and {pair[1]}: {pair[2]:.2f}")

Highly Correlated Pairs (above threshold of 0.7):
grade_1 and grade_2: 0.85
grade_1 and final_grade: 0.80
grade_2 and final_grade: 0.90
guardian_father and guardian_mother: -0.81

**Get X and y**

In [17]:
y = encoded_df["final_grade"]
X = encoded_df[["grade_2","grade_1","absences","family_relationship","age"]]

In [ ]:
y

0       6
1       6
2      10
3      15
4      10
       ..
390     9
391    16
392     7
393    10
394     9
Name: final_grade, Length: 395, dtype: int64

**Train - test split**

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Linear regression model**

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate MSE and R-squared for training set
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)

# Calculate MSE and R-squared for testing set
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Print the results
print(f"Training MSE: {train_mse:.2f}")
print(f"Training RMSE: {(train_mse)**0.5:.2f}")
print(f"Training R-squared: {train_r2:.2f}")
print(f"Testing MSE: {test_mse:.2f}")
print(f"Testing RMSE: {(test_mse)**0.5:.2f}")
print(f"Testing R-squared: {test_r2:.2f}")

Training MSE: 3.31
Training RMSE: 1.82
Training R-squared: 0.84
Testing MSE: 4.20
Testing RMSE: 2.05
Testing R-squared: 0.80

In [ ]:
y_test.mean(), y_test.min(), y_test.max()

(10.772151898734178, 0, 19)

**kNN model**

In [10]:
from sklearn.neighbors import KNeighborsRegressor

# Create and train the k-NN model
knn_model = KNeighborsRegressor(n_neighbors=5)  # You can adjust the number of neighbors
knn_model.fit(X_train, y_train)

# Make predictions
knn_y_train_pred = knn_model.predict(X_train)
knn_y_test_pred = knn_model.predict(X_test)

# Evaluate the k-NN model
knn_train_mse = mean_squared_error(y_train, knn_y_train_pred)
knn_train_r2 = r2_score(y_train, knn_y_train_pred)
knn_test_mse = mean_squared_error(y_test, knn_y_test_pred)
knn_test_r2 = r2_score(y_test, knn_y_test_pred)

print(f"k-NN Training MSE: {knn_train_mse:.2f}")
print(f"k-NN Training RMSE: {(knn_train_mse)**0.5:.2f}")
print(f"k-NN Training R-squared: {knn_train_r2:.2f}")
print(f"k-NN Testing MSE: {knn_test_mse:.2f}")
print(f"k-NN Testing RMSE: {(knn_test_mse)**0.5:.2f}")
print(f"k-NN Testing R-squared: {knn_test_r2:.2f}")

k-NN Training MSE: 1.64
k-NN Training RMSE: 1.28
k-NN Training R-squared: 0.92
k-NN Testing MSE: 3.45
k-NN Testing RMSE: 1.86
k-NN Testing R-squared: 0.83

**Decision tree**

In [11]:
from sklearn.tree import DecisionTreeRegressor

# Create and train the decision tree model
dt_model = DecisionTreeRegressor(random_state=42)  # You can adjust hyperparameters
dt_model.fit(X_train, y_train)

# Make predictions
dt_y_train_pred = dt_model.predict(X_train)
dt_y_test_pred = dt_model.predict(X_test)

# Evaluate the decision tree model
dt_train_mse = mean_squared_error(y_train, dt_y_train_pred)
dt_train_r2 = r2_score(y_train, dt_y_train_pred)
dt_test_mse = mean_squared_error(y_test, dt_y_test_pred)
dt_test_r2 = r2_score(y_test, dt_y_test_pred)

print(f"Decision Tree Training MSE: {dt_train_mse:.2f}")
print(f"Decision Tree Training RMSE: {(dt_train_mse)**0.5:.2f}")
print(f"Decision Tree Training R-squared: {dt_train_r2:.2f}")
print(f"Decision Tree Testing MSE: {dt_test_mse:.2f}")
print(f"Decision Tree Testing RMSE: {(dt_test_mse)**0.5:.2f}")
print(f"Decision Tree Testing R-squared: {dt_test_r2:.2f}")

Decision Tree Training MSE: 0.02
Decision Tree Training RMSE: 0.13
Decision Tree Training R-squared: 1.00
Decision Tree Testing MSE: 5.05
Decision Tree Testing RMSE: 2.25
Decision Tree Testing R-squared: 0.75

**Random forest model**

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Create and train the random forest model
rf_model = RandomForestRegressor(max_features = 49, min_samples_split = 10, n_estimators = 100)  # You can adjust hyperparameters
rf_model.fit(X_train, y_train)

# Make predictions
rf_y_train_pred = rf_model.predict(X_train)
rf_y_test_pred = rf_model.predict(X_test)

# Evaluate the random forest model
rf_train_mse = mean_squared_error(y_train, rf_y_train_pred)
rf_train_r2 = r2_score(y_train, rf_y_train_pred)
rf_test_mse = mean_squared_error(y_test, rf_y_test_pred)
rf_test_r2 = r2_score(y_test, rf_y_test_pred)
mae_train = mean_absolute_error(y_train, rf_y_train_pred)
mae_test = mean_absolute_error(y_test, rf_y_test_pred)


print(f"Random Forest Training MSE: {rf_train_mse:.2f}")
print(f"Random Forest Training RMSE: {(rf_train_mse)**0.5:.2f}")
print(f"Random Forest Training R-squared: {rf_train_r2:.2f}")
print(f"Random Forest Testing MSE: {rf_test_mse:.2f}")
print(f"Random Forest Testing RMSE: {(rf_test_mse)**0.5:.2f}")
print(f"Random Forest Testing R-squared: {rf_test_r2:.2f}")

print(f"RF Training MAE: {mae_train:.2f}")
print(f"RF Testing MAE: {mae_test:.2f}")

Random Forest Training MSE: 1.10
Random Forest Training RMSE: 1.05
Random Forest Training R-squared: 0.95
Random Forest Testing MSE: 3.02
Random Forest Testing RMSE: 1.74
Random Forest Testing R-squared: 0.85
RF Training MAE: 0.64
RF Testing MAE: 1.06

Hyperarameter tuning for Random forest

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define the hyperparameter grid to search
param_grid = {
    'n_estimators': [500, 1000],
    #'max_depth': [None, 5, 10, 15], #Try bring this in
    'min_samples_split': range(50, 100, 10), #Change the first '10' to reduce overfitting --> Try 40, 30, (20, 60)
    'max_features': range(1, len(X.columns), 2) #Change to 1,...
}

rf_model = RandomForestRegressor(random_state=42)
# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid,
                           scoring='neg_mean_squared_error', cv= 3 , verbose=5)

# Fit the GridSearchCV object to the training data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print(f"Best Hyperparameters: {best_params}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Make predictions using the best model
y_pred_test = best_rf_model.predict(X_test)
y_pred_train = best_rf_model.predict(X_train)

# Evaluate the best model
mse_train = mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

print(f"MSE Train: {mse_train:.2f}")
print(f"RMSE Train: {(mse_train)**0.5:.2f}")
print(f"R-squared Train: {r2_train:.2f}")
print(f"MSE Test: {mse_test:.2f}")
print(f"RMSE Test: {(mse_test)**0.5:.2f}")
print(f"R-squared Test: {r2_test:.2f}")

Fitting 3 folds for each of 260 candidates, totalling 780 fits
[CV 1/3] END max_features=1, min_samples_split=50, n_estimators=500;, score=-17.451 total time=   0.7s
[CV 2/3] END max_features=1, min_samples_split=50, n_estimators=500;, score=-17.500 total time=   1.7s
[CV 3/3] END max_features=1, min_samples_split=50, n_estimators=500;, score=-18.271 total time=   3.7s

KeyboardInterrupt:

**XGBoost model**

In [ ]:
import xgboost as xgb

# Create and train the XGBoost model
xgb_model = xgb.XGBRegressor(alpha = 5, colsample_bynode = 0.8, eta = 0.1, n_estimators = 100, subsample = 1) # You can adjust hyperparameters
xgb_model.fit(X_train, y_train)

# Make predictions
xgb_y_train_pred = xgb_model.predict(X_train)
xgb_y_test_pred = xgb_model.predict(X_test)

# Evaluate the XGBoost model
xgb_train_mse = mean_squared_error(y_train, xgb_y_train_pred)
xgb_train_r2 = r2_score(y_train, xgb_y_train_pred)
xgb_test_mse = mean_squared_error(y_test, xgb_y_test_pred)
xgb_test_r2 = r2_score(y_test, xgb_y_test_pred)
mae_train = mean_absolute_error(y_train, xgb_y_train_pred)
mae_test = mean_absolute_error(y_test, xgb_y_test_pred)

print(f"XGBoost Training MSE: {xgb_train_mse:.2f}")
print(f"XGBoost Training RMSE: {(xgb_train_mse)**0.5:.2f}")
print(f"XGBoost Training R-squared: {xgb_train_r2:.2f}")
print(f"XGBoost Testing MSE: {xgb_test_mse:.2f}")
print(f"XGBoost Testing RMSE: {(xgb_test_mse)**0.5:.2f}")
print(f"XGBoost Testing R-squared: {xgb_test_r2:.2f}")

print(f"XGBoost Training MAE: {mae_train:.2f}")
print(f"XGBoost Testing MAE: {mae_test:.2f}")

XGBoost Training MSE: 0.96
XGBoost Training RMSE: 0.98
XGBoost Training R-squared: 0.95
XGBoost Testing MSE: 14.37
XGBoost Testing RMSE: 3.79
XGBoost Testing R-squared: 0.30
XGBoost Training MAE: 0.74
XGBoost Testing MAE: 3.00

Hyperparameter tuning for XGBoost

In [ ]:
# Define the parameter grid for XGBoost
from sklearn.model_selection import GridSearchCV
!pip install --upgrade scikit-learn xgboost
# Restart the kernel after installing
param_grid_xgb = {
    'n_estimators': [100, 200],
    #'max_depth': [3, 5, 7],
    'eta': [0.01, 0.05, 0.1, 0.2, 0.3],
    'subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1],
    'colsample_bynode': [0.5, 0.6, 0.7, 0.8, 0.9, 1],
    'alpha': [0, 0.1, 0.5, 1, 5, 10],
    'lambda': [0, 0.1, 0.5, 1, 5, 10]
}
# Create the XGBoost model
xgb_model = xgb.XGBRegressor(random_state=42)
# Perform GridSearchCV for hyperparameter tuning
grid_search_xgb = GridSearchCV(estimator=xgb_model, param_grid=param_grid_xgb,
                              scoring='neg_mean_squared_error', cv=2, verbose=5)
grid_search_xgb.fit(X_train, y_train)
# Print the best hyperparameters
print("Best hyperparameters:", grid_search_xgb.best_params_)
# Evaluate the best model
best_xgb_model = grid_search_xgb.best_estimator_
xgb_y_pred_train = best_xgb_model.predict(X_train)  # Predictions for training data
xgb_y_pred_test = best_xgb_model.predict(X_test)  # Predictions for testing data
xgb_mse_train = mean_squared_error(y_train, xgb_y_pred_train)
xgb_r2_train = r2_score(y_train, xgb_y_pred_train)
xgb_mse_test = mean_squared_error(y_test, xgb_y_pred_test)
xgb_r2_test = r2_score(y_test, xgb_y_pred_test)


print(f"XGBoost best model Train MSE: {xgb_mse_train:.2f}")
print(f"XGBoost best model Train RMSE: {xgb_mse_train**0.5:.2f}")
print(f"XGBoost best model Train R-squared: {xgb_r2_train:.2f}")
print(f"XGBoost best model Test MSE: {xgb_mse_test:.2f}")
print(f"XGBoost best model Test RMSE: {xgb_mse_test**0.5:.2f}")
print(f"XGBoost best model Test R-squared: {xgb_r2_test:.2f}")

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.1.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost) (2.23.4)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The XGBRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(

AttributeError: 'super' object has no attribute '__sklearn_tags__'